# Generated by Django 2.2.2 on 2022-03-01 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=255)),
                ('patient_last_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_phone_number', models.CharField(max_length=20)),
                ('patient_location', models.CharField(max_length=255)),
                ('patient_gender', models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('appointment_datetime', models.DateTimeField()),
                ('symptom_description', models.TextField(max_length=1025)),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('has_already_appointed', models.BooleanField(default=False)),
                ('report_file', models.FileField(blank=True, default='hospital/default.png', null=True, upload_to='doctor/appointment/report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
