# Generated by Django 2.2.2 on 2022-03-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20220301_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='appointment_datetime',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
