# Generated by Django 2.2.2 on 2022-03-08 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0003_auto_20220301_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='reffer_doctor',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='reffer_doctor',
            field=models.ManyToManyField(null=True, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
