# Generated by Django 2.2.2 on 2022-03-08 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0004_auto_20220308_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='reffer_doctor',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='reffer_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
