# Generated by Django 2.2.2 on 2022-02-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0006_auto_20220227_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=225)),
                ('hospital_code', models.CharField(max_length=20, unique=True)),
                ('in_service', models.BooleanField(default=True)),
                ('hospital_provience', models.CharField(max_length=255)),
                ('hospital_city', models.CharField(max_length=255)),
                ('hospital_location', models.CharField(max_length=255)),
                ('emergency_phone', models.TextField(max_length=1024)),
                ('reception_phone', models.TextField(max_length=1024)),
                ('hospital_map_location_url', models.URLField(max_length=300)),
                ('hospital_webiste_url', models.URLField(max_length=500)),
                ('hospital_logo', models.ImageField(default='hospital/default.png', upload_to='hospital/logo')),
                ('hospital_image', models.ImageField(default='hospital/default.png', upload_to='hospital/images')),
                ('is_inservice', models.BooleanField(default=True)),
                ('hospital_services', models.ManyToManyField(to='services.HospitalServiceModule')),
            ],
        ),
    ]
