# Generated by Django 2.2.2 on 2022-02-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalmodel',
            name='is_inservice',
        ),
    ]
