# Generated by Django 2.2.2 on 2022-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospitalmodel_is_inservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='hospital_description',
            field=models.TextField(blank=True, max_length=1040, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalmodel',
            name='hospital_image',
            field=models.ImageField(blank=True, default='hospital/default.png', null=True, upload_to='hospital/images'),
        ),
        migrations.AlterField(
            model_name='hospitalmodel',
            name='hospital_logo',
            field=models.ImageField(blank=True, default='hospital/default.png', null=True, upload_to='hospital/logo'),
        ),
        migrations.AlterField(
            model_name='hospitalmodel',
            name='hospital_map_location_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalmodel',
            name='hospital_webiste_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalmodel',
            name='reception_phone',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
