# Generated by Django 2.2.2 on 2022-03-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20220227_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmodel',
            name='hospital_image',
            field=models.ImageField(blank=True, default='hospital/default_hospital.png', null=True, upload_to='hospital/images'),
        ),
    ]
