# Generated by Django 2.2.2 on 2022-02-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220227_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuserprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicuserprofile',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
