# Generated by Django 2.2.2 on 2022-02-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_basicuserprofile_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuserprofile',
            name='phone_no',
        ),
    ]
