# Generated by Django 2.2.2 on 2022-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_basicuserprofile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserprofile',
            name='test_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
