# Generated by Django 2.2.2 on 2022-02-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20220227_1159'),
        ('accounts', '0007_basicuserprofile_test_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicuserprofile',
            old_name='test_field',
            new_name='median_name',
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='availablility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='current_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='doctor_licence',
            field=models.ImageField(blank=True, default='hospital/default.png', null=True, upload_to='doctor/licence_image'),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='hospital',
            field=models.ManyToManyField(null=True, to='hospital.HospitalModel'),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='medical_specialties',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='office_phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='personal_phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='private_gmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='hospital/default.png', null=True, upload_to='doctor/profile_image'),
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='studied_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
