# Generated by Django 2.2.2 on 2022-02-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220228_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserprofile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
