# Generated by Django 2.2.2 on 2022-03-01 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_basicuserprofile_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='basicuserprofile',
            name='reffer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
