# Generated by Django 2.2.2 on 2022-03-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220301_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuserprofile',
            name='doctor_licence',
            field=models.FileField(blank=True, null=True, upload_to='doctor/licence_image'),
        ),
    ]
