# Generated by Django 2.2.2 on 2022-03-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220301_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuserprofile',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.HospitalModel'),
        ),
    ]
