# Generated by Django 2.2.2 on 2022-03-01 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220301_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuserprofile',
            name='availablility',
            field=models.CharField(blank=True, choices=[('anytime', 'Anytime'), ('onshift', 'ON Shift')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicuserprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='basicuserprofile',
            name='highest_degree',
            field=models.CharField(blank=True, choices=[('mbbs', 'M.B.B.S'), ('md', 'M.D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicuserprofile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicuserprofile',
            name='medical_specialties',
            field=models.CharField(blank=True, choices=[('dermatologists', 'Dermatologists'), ('Infectious_disease_doctors', 'Infectious disease doctors'), ('ophthalmologists', 'Ophthalmologists'), ('obstetrician', 'Obstetrician'), ('cardiologists', 'Cardiologists'), ('endocrinologists', 'Endocrinologists'), ('gastroenterologists', 'Gastroenterologists'), ('nephrologists', 'Nephrologists'), ('urologists', 'Urologists'), ('pulmonologists', 'Pulmonologists'), ('rheumatologists', 'Rheumatologists'), ('radiologists', 'Radiologists'), ('oncologists', 'Oncologists'), ('psychiatrists', 'Psychiatrists'), ('neurologists', 'Neurologists'), ('otolaryngologists', 'Otolaryngologists'), ('anesthesiologists', 'Anesthesiologists')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basicuserprofile',
            name='reffer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basicuserprofile',
            name='studied_in',
            field=models.CharField(blank=True, choices=[('incountry', 'In Country'), ('outcountry', 'Out Country')], max_length=255, null=True),
        ),
    ]
