# Generated by Django 2.2.2 on 2022-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220301_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuserprofile',
            name='doctor_regestriation_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
