# Generated by Django 2.2.2 on 2022-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20220301_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserprofile',
            name='appointment_per_day',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
