# Generated by Django 2.2.2 on 2022-02-24 14:52

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalServiceModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Please Enter Your Services', max_length=255)),
                ('service_desc', models.TextField(help_text='PleaseEnter Your Services', max_length=1040)),
                ('is_active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
                ('service_image', models.ImageField(default='services/default_service.png', upload_to='services')),
            ],
        ),
    ]
