# Generated by Django 2.2.2 on 2022-02-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalservicemodule',
            name='service_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
