# Generated by Django 2.2.2 on 2022-02-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_hospitalservicemodule_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalservicemodule',
            old_name='is_active',
            new_name='is_ineffect',
        ),
    ]
