# Generated by Django 2.2.2 on 2022-02-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220224_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservicemodule',
            name='service_desc',
            field=models.TextField(max_length=1040),
        ),
        migrations.AlterField(
            model_name='hospitalservicemodule',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
