# Generated by Django 2.2.2 on 2022-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220224_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservicemodule',
            name='service_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
