# Generated by Django 2.2.2 on 2020-10-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCaptchaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_version', models.PositiveIntegerField(blank=True, choices=[(1, 'V2'), (2, 'V2 Invisible'), (3, 'V3')], null=True)),
                ('site_key', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteLogoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100)),
                ('copyright', models.CharField(blank=True, max_length=200, null=True)),
                ('captcha_setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.WebsiteCaptchaModel')),
                ('logo_setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.WebsiteLogoModel')),
            ],
        ),
    ]
