# Generated by Django 2.2.2 on 2020-10-07 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettingmodel',
            name='captcha_setting',
        ),
        migrations.RemoveField(
            model_name='websitesettingmodel',
            name='logo_setting',
        ),
        migrations.AddField(
            model_name='websitesettingmodel',
            name='captcha_version',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'V2'), (2, 'V2 Invisible'), (3, 'V3')], null=True),
        ),
        migrations.AddField(
            model_name='websitesettingmodel',
            name='logo_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesettingmodel',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websitesettingmodel',
            name='site_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='WebsiteCaptchaModel',
        ),
        migrations.DeleteModel(
            name='WebsiteLogoModel',
        ),
    ]
