# Generated by Django 2.2.2 on 2020-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20201007_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettingmodel',
            name='enable_captcha',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
