# Generated by Django 2.2.2 on 2020-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_websitesettingmodel_enable_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettingmodel',
            name='favicon',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
