# Generated by Django 2.2.2 on 2022-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_websitesettingmodel_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettingmodel',
            name='show_website_name',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
