# Generated by Django 2.2.2 on 2022-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaVaccineCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=255)),
                ('provience', models.CharField(choices=[('Provience 1', 'Provience 1'), ('Madesh', 'Madesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], max_length=50)),
                ('district', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('help_phone_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('vaccine_batch', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccine_type', models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second'), ('Buster', 'Buster'), ('Other', 'Other')], max_length=255, null=True)),
                ('age_group', models.BooleanField(default=True)),
                ('age_from', models.IntegerField(blank=True, null=True)),
                ('age_to', models.IntegerField(blank=True, null=True)),
                ('provide_from', models.DateField()),
                ('provide_to', models.DateField()),
                ('service_type', models.CharField(choices=[('First Come First', 'First Come First'), ('Anytime Sevice', 'Anytime Service'), ('Specific People', 'Specific People')], max_length=255)),
                ('is_quota', models.BooleanField(default=False)),
                ('quota_quantity', models.IntegerField(blank=True, null=True)),
                ('in_effect', models.BooleanField(default=True)),
            ],
        ),
    ]
