# Generated by Django 2.2.2 on 2022-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinecenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavaccinecenter',
            name='vaccine_type',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second'), ('Booster', 'Booster'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
