# Generated by Django 2.2.2 on 2021-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='department',
            field=models.IntegerField(choices=[(1, 'CIVIL'), (2, 'COMPUTER'), (3, 'IT'), (4, 'SOFTWARE')]),
        ),
    ]
